version: '3.8'
services:
  db:
    image: postgres:15
    container_name: agro-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    container_name: agro-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_test
    ports:
      - '5433:5432'
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  api:
    build: .
    container_name: agro-api
    command: pnpm start:dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
      - db-test
    env_file:
      - .env.docker

volumes:
  pgdata:
  pgdata_test:
